trigger:
  branches:
    include:
    - master

pool:
  name: $(kubernetesLinuxAgentPoolName)

variables:
- group: PipelineSoftwareVersions
- group: ConnectorLibraries

steps:
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.3.7'

- task: gitversion/execute@0
  displayName: Run GitVersion
  inputs:
    useConfigFile: true
    configFilePath: 'git-version.yml'

- task: npmAuthenticate@0
  inputs:
    workingFile: ./.npmrc
    customEndpoint: 'NPM JS Registry'
  displayName: 'Npm Authenticate'

- script: yarn install
  displayName: 'Yarn install'

- script: yarn build
  displayName: 'Yarn build'

- script: yarn publish --new-version $(GitVersion.SemVer) --no-git-tag-version --access public
  workingDirectory: ./build
  displayName: 'Yarn publish'

- script: 'git push https://$(GitHubToken)@github.com/templafy/DeliveryConnectorLibrary.git'
  displayName: Push to GitHub
