trigger:
  branches:
    include:
    - master

pool:
  name: $(kubernetesLinuxAgentPoolName)

variables:
- group: PipelineSoftwareVersions
- group: ConnectorLibraries

resources:
  repositories:
  - repository: templates
    name: Pipelines
    type: git
    ref: refs/heads/master

steps:
- template: pipeline-templates/gitversion-task.yml@templates
  parameters:
    gitVersionVersion: $(gitVersionVersion)

- task: npmAuthenticate@0
  inputs:
    workingFile: ./.npmrc
    customEndpoint: 'NPM JS Registry'
  displayName: 'Npm Authenticate'

- script: yarn install
  displayName: 'Yarn install'

- script: yarn build
  displayName: 'Yarn build'

- script: |
    latestPublishedPackage=$(yarn info @templafy/delivery-connector-library@$(GitVersion.SemVer) --json | jq .data | jq  -r '.["dist-tags"]["latest"]')
    echo $latestPublishedPackage
    if [[ $latestPublishedPackage == $(GitVersion.SemVer) ]]; then
      echo "Npm package with version $(GitVersion.SemVer) is already pushed."
      echo "##vso[task.setvariable variable=packageExists]true"
    else
      echo "Npm package with version $(GitVersion.SemVer) is not pushed."
      echo "##vso[task.setvariable variable=packageExists]false"
    fi 
  displayName: 'Check if package was already published'

- script: yarn publish --new-version $(GitVersion.SemVer) --no-git-tag-version --access public
  workingDirectory: ./build
  displayName: 'Yarn publish'
  condition: ne(variables['packageExists'],'true')

- script: 'git push https://$(GitHubToken)@github.com/templafy/DeliveryConnectorLibrary.git'
  displayName: Push to GitHub