trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-18.04

variables:
  - group: DeliveryIntegrationLibrary

steps:
  - task: UseGitVersion@5
    inputs:
      versionSpec: '5.x'
      useConfigFile: true
      configFilePath: 'git-version.yml'

  - task: npmAuthenticate@0
    inputs:
      workingFile: ./.npmrc
      customEndpoint: 'NPM JS Registry'
    displayName: 'Npm Authenticate'

  - script: yarn install
    displayName: 'Yarn install'

  - script: yarn build
    displayName: 'Yarn build'

  - script: yarn publish --new-version $(GitVersion.SemVer) --no-git-tag-version --access public
    workingDirectory: ./build
    displayName: 'Yarn publish'

  - script: 'git push https://$(GitHubToken)@github.com/templafy/DeliveryIntegrationLibrary.git'
    displayName: Push to GitHub
