trigger:
  branches:
    include:
    - master

pool:
  name: $(kubernetesLinuxAgentPoolName)

resources:
  repositories:
    - repository: templates
      name: Pipelines
      type: git
      ref: refs/tags/0.4.19

variables:
- group: PipelineSoftwareVersions
- group: ConnectorLibraries

steps:
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '6.0.0-beta.3'

- task: gitversion/execute@0
  displayName: Run GitVersion
  inputs:
    useConfigFile: true
    configFilePath: 'git-version.yml'

- task: npmAuthenticate@0
  inputs:
    workingFile: ./.npmrc
    customEndpoint: 'NPM JS Registry'
  displayName: 'Npm Authenticate'

- script: yarn install
  displayName: 'Yarn install'

- script: yarn build
  displayName: 'Yarn build'

- template: pipeline-templates/check-npm-package-exists-within-a-job.yml@templates
  parameters:
    packageName: 'delivery-connector-library'
    packageVersion: $(GitVersion.SemVer)
  name: 

- script: yarn publish --new-version $(GitVersion.SemVer) --no-git-tag-version --access public
  workingDirectory: ./build
  displayName: 'Yarn publish'
  condition: ne($(packageExists),true)

- script: 'git push https://$(GitHubToken)@github.com/templafy/DeliveryConnectorLibrary.git'
  displayName: Push to GitHub